# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/scraper.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'protos/scraper.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14protos/scraper.proto\x12\x07scraper\"\x1b\n\x07Request\x12\x10\n\x08\x66ilmName\x18\x01 \x01(\t\"\x1b\n\x08Response\x12\x0f\n\x07scraped\x18\x01 \x01(\x05\x32\x42\n\x07Scraper\x12\x37\n\x0eScrapeFilmInfo\x12\x10.scraper.Request\x1a\x11.scraper.Response\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.scraper_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUEST']._serialized_start=33
  _globals['_REQUEST']._serialized_end=60
  _globals['_RESPONSE']._serialized_start=62
  _globals['_RESPONSE']._serialized_end=89
  _globals['_SCRAPER']._serialized_start=91
  _globals['_SCRAPER']._serialized_end=157
# @@protoc_insertion_point(module_scope)
